---
- hosts: all
  pre_tasks:
    - name: Ensure Centos 7
      assert:
        that:
          - ansible_distribution == 'CentOS'
          - ansible_distribution_version is version('7', '>=')
          - ansible_distribution_version is version('8', '<)
        msg: "Unfortunately for now only CentOS-7 is supported."

- hosts: elastic_nodes
  roles:
    - role: firewall
      tags:
        - bake
        - elk

- hosts: kibana_nodes
  roles:
    - role: firewall
      tags:
        - bake
        - kibana

- hosts: elastic_nodes
  roles:
    - role: elasticsearch
      tags:
        - elk

- hosts: kibana_nodes
  roles:
    - role: kibana
      tags:
        - kibana
...
